<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find agri_bot)/urdf/materials.xacro" />
<xacro:include filename="$(find agri_bot)/urdf/properties.xacro" />

<xacro:property name="chassis_length"  value = "0.5"/>
<xacro:property name="chassis_width"   value = "0.3"/>
<xacro:property name="chassis_height"  value = "0.1"/>
<xacro:property name="chassis_mass"    value = "0.1"/>
<xacro:property name="wheel_radius"    value = "0.1"/>
<xacro:property name="wheel_thickness" value = "0.1"/>
<xacro:property name="wheel_mass"      value = "0.1"/>

<link name="base_link"/>

<link name="chassis_link">
    <visual>
        <geometry>
            <box size="0.5 0.3 0.1"/>    
        </geometry>
        <material name="green"/>
    </visual>
    <collision>
        <geometry>
            <box size="0.5 0.3 0.1"/>    
        </geometry>
        <material name="green"/>
    </collision>
    <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
      <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
</link>

<gazebo reference="chassis_link">
    <material>Gazebo/Blue</material>
</gazebo>

<link name="front_right_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="front_right_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<link name="front_left_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="front_left_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<link name="rear_right_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="rear_right_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<link name="rear_left_wheel">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="rear_left_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
</joint>

<joint name="fr_to_chassis" type="continuous">
    <parent link="chassis_link"/>
    <child link="front_right_wheel"/>
    <origin xyz = "${chassis_length/2 - chassis_length/8} ${chassis_width - 0.1} -${chassis_height/2}" rpy= "${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<joint name="fl_to_chassis" type="continuous">
    <parent link="chassis_link"/>
    <child link="front_left_wheel"/>
    <origin xyz = "${chassis_length/2 - chassis_length/8} -${chassis_width - 0.1} -${chassis_height/2}" rpy= "-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<joint name="rr_to_chassis" type="continuous">
    <parent link="chassis_link"/>
    <child link="rear_right_wheel"/>
    <origin xyz = "-${chassis_length/2 - chassis_length/8} ${chassis_width - 0.1} -${chassis_height/2}" rpy= "${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<joint name="rl_to_chassis" type="continuous">
    <parent link="chassis_link"/>
    <child link="rear_left_wheel"/>
    <origin xyz = "-${chassis_length/2 - chassis_length/8} -${chassis_width - 0.1} -${chassis_height/2}" rpy= "-${pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

</robot>